import type { Metadata } from "next";
import "./globals.css";
import { Container } from "@/components/Container";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import Link from "next/link";

export const metadata: Metadata = {
  title: {
    default: "The Blog - Next.js",
    template: "The Blog | %s"
  },
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="en" className="dark min-h-screen">
      <body>
        <Container>
          <Link href="/">
            <Header />
          </Link>
          {children}
          <Footer />
        </Container>
      </body>
    </html>
  );
}
